version: '3'

services:
  dev-front-lendos:
    container_name: dev-front-lendos
    image: registry.int.zpoken.io/lendos/front:dev
    restart: always
    build:
      context: .
      dockerfile: ./apps/evm/Dockerfile
      args:
        NODE: development
    ports:
      - 9011:3000

  web:
    container_name: web
    build:
      context: .
      dockerfile: ./apps/fuel/Dockerfile
      args:
        NODE: production
    restart: always
    ports:
      - 9000:3000

