import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';
import { headers } from 'next/headers';
import { cookieToInitialState } from 'wagmi';
import { montserrat, aldrich } from '@lendos/ui/src/fonts';
import { wagmiConfig } from './config/connectors';
import './globals.css';
import { Providers } from './providers';
import { ChildrenProps } from './types/common';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

async function RootLayout({ children }: ChildrenProps) {
  const head = await headers();
  const wagmiInitialState = cookieToInitialState(wagmiConfig, head.get('cookie'));

  return (
    <html lang='en'>
      <body className={`${aldrich.variable} ${montserrat.variable} font-sans`}>
        <AppRouterCacheProvider>
          <Providers initialState={wagmiInitialState}>{children}</Providers>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}

export default RootLayout;
