import { MuiLayout } from '@lendos/ui/src/layouts/MuiLayout';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v13-appRouter';
import type { Metadata } from 'next';
import React from 'react';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body>
        <AppRouterCacheProvider>
          <MuiLayout>{children}</MuiLayout>
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}

export default RootLayout;
